openapi: 3.0.3
info:
  title: Node service rest api
  version: 1.0.0
components:
  schemas: {}
paths:
  /ws/:
    get:
      responses:
        "200":
          description: Default Response
  /api/:
    get:
      responses:
        "200":
          description: Default Response
servers: []
